### ISSUE TITLE
Party List Checklist

### ISSUE THREAD

**Issue by ViniBGoulart** [ViniBGoulart/party-list#23]
## Feat
- [ ] Event Flyer
- [ ] Sign Up page
- [ ] Sign button when not logged
- [ ] User avatar
- [ ] Event page
- [ ] Event Owner
- [ ] Event participants and generate the list

## Fix style
- [ ] Event card minimum size
- [ ] Footer size
- [ ] Username not showing in mobile
